musicapp/forms.py
import os
import imghdr
from flask import current_app
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from flask_login import current_user
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from musicapp.models import User


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[
                           DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[
                             DataRequired(), Length(min=6, max=40)])
    confirm_password = PasswordField('Confirm Password', validators=[
                                     DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError(
                f'{username.data} is taken. Please choose a different Username.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError(
                f'{email.data} is taken. Please choose a different Email.')


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[
                             DataRequired(), Length(min=6, max=40)])
    remember = BooleanField('Remember me')
    submit = SubmitField('Login')


class UpdateAccountForm(FlaskForm):
    username = StringField('Username', validators=[
                           DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError(
                    f'{username.data} is taken. Please choose a different Username.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError(
                    f'{email.data} is taken. Please choose a different Email.')


class SongForm(FlaskForm):
    song = FileField('Select an MP3 file: ', validators=[
                     DataRequired()])
    submit = SubmitField('Upload')

    def validate_song(self, song):
        if song.data:
            _, ext = os.path.splitext(song.data.filename)
            ext = ext.lower()
            if ext != '.mp3':
                raise ValidationError('Only mp3 files allowed.')

            if song.data.content_length > current_app.config['MAX_CONTENT_LENGTH']:
                raise ValidationError(
                    'Song size too large! Upload songs of size less than 20MB.')

class SongMetadataForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    artist = StringField('Artist', validators=[DataRequired()])
    album = StringField('Album', validators=[DataRequired()])
    submit = SubmitField('Save Song')


class SearchForm(FlaskForm):
    search_input_text = StringField('What you want to listend to..?', validators=[DataRequired()])
    submit = SubmitField('Search')

class RequestResetForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError(
                f'No such user exists! Please check your email and try again.')

class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[
                             DataRequired(), Length(min=6, max=40)])
    confirm_password = PasswordField('Confirm Password', validators=[
                                     DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')

musicapp/songs/forms.py
import os
from flask import current_app
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError


class SongForm(FlaskForm):
    song = FileField('Select an MP3 file: ', validators=[
                     DataRequired(), FileAllowed(['mp3'], 'mp3 files only!')])
    submit = SubmitField('Upload')

    def validate_song(self, song):
        if song.data:
            _, ext = os.path.splitext(song.data.filename)
            ext = ext.lower()
            if ext != '.mp3':
                raise ValidationError('Only mp3 files allowed.')

            if song.data.content_length > current_app.config['MAX_CONTENT_LENGTH']:
                raise ValidationError(
                    'Song size too large! Upload songs of size less than 20MB.')


class SongMetadataForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    artist = StringField('Artist', validators=[DataRequired()])
    album = StringField('Album', validators=[DataRequired()])
    submit = SubmitField('Save Song')


class SearchForm(FlaskForm):
    search_input_text = StringField(
        'What you want to listend to..?', validators=[DataRequired()])
    submit = SubmitField('Search')

musicapp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from musicapp.config import Config


mail = Mail()
db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    mail.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    from musicapp.users.routes import users
    from musicapp.songs.routes import songs
    from musicapp.main.routes import main
    from musicapp.errors.handlers import errors
    app.register_blueprint(users)
    app.register_blueprint(songs)
    app.register_blueprint(main)
    app.register_blueprint(errors)

    return app

musicapp/main/routes.py
from flask import render_template, request, Blueprint
from flask_login import current_user, login_required
from musicapp.models import Song
from musicapp.songs.forms import SearchForm

main = Blueprint('main', __name__)


@main.context_processor
def layout():
    form = SearchForm()
    return dict(form=form)


@main.route('/')
@main.route('/home')
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    songs = Song.query.filter_by(
        owner_id=current_user.id).paginate(page=page, per_page=12)
    return render_template('home.html', songs=songs)


@main.route('/collection')
@login_required
def collection():
    page = request.args.get('page', 1, type=int)
    songs = Song.query.paginate(page=page, per_page=12)
    return render_template('collection.html', title='All Songs', songs=songs)

musicapp/songs/routes.py
import os
from flask import render_template, url_for, flash, redirect, request, send_file, abort, Blueprint, current_app as app
from flask_login import current_user, login_required
from sqlalchemy import or_
import eyed3

from musicapp.models import Song
from musicapp import db
from musicapp.songs.forms import SongForm, SearchForm, SongMetadataForm
from musicapp.songs.utils import save_song

songs = Blueprint('songs', __name__)


@songs.context_processor
def layout():
    form = SearchForm()
    return dict(form=form)


@songs.route('/song/upload', methods=['GET', 'POST'])
@login_required
def upload():
    form = SongForm()
    if form.validate_on_submit():
        song_file = form.song.data
        filename = save_song(song_file)
        file_path = os.path.join(
            app.config['UPLOAD_FOLDER'], filename)
        audio = eyed3.load(file_path)

        title = audio.tag.title if audio.tag.title else "Unknown Title"
        artist = audio.tag.artist if audio.tag.artist else "Unknown Artist"
        album = audio.tag.album if audio.tag.album else "Unknown Album"

        song = Song(title=title, artist=artist,
                    album=album, owner=current_user, filename=filename)
        db.session.add(song)
        db.session.commit()

        return redirect(url_for('songs.song_metadata', id=song.id))

    return render_template('upload_song.html', title='Upload Song', form=form)


@songs.route('/song/upload/metadata/<int:id>', methods=['GET', 'POST'])
@login_required
def song_metadata(id):
    form = SongMetadataForm()
    song = Song.query.get_or_404(id)
    if song.owner != current_user:
        abort(403)

    if form.validate_on_submit():
        song.title = form.title.data
        song.artist = form.artist.data
        song.album = form.album.data
        db.session.commit()

        song_path = os.path.join(
            app.root_path, app.config['UPLOAD_FOLDER'], song.filename)
        audio = eyed3.load(song_path)
        audio.tag.title = song.title
        audio.tag.artist = song.artist
        audio.tag.album = song.album
        audio.tag.save()

        flash(f'Song `{form.title.data}` has been uploaded!', 'success')
        return redirect(url_for('songs.upload'))
    elif request.method == 'GET':
        form.title.data = song.title
        form.artist.data = song.artist
        form.album.data = song.album
    return render_template('song_metadata.html', title='Edit song details', form=form)


@songs.route('/song/play/<int:song_id>')
@login_required
def song(song_id):
    song = Song.query.get_or_404(song_id)
    song_file = url_for('static', filename='uploads/' + song.filename)
    return render_template('song.html', song=song, music=song_file)


@songs.route('/song/delete/<int:song_id>', methods=['POST'])
@login_required
def delete(song_id):
    song = Song.query.get_or_404(song_id)
    # only owner of song can delete it
    if song.owner != current_user:
        abort(403)

    song_title = song.title

    # delete the file from the server
    song_path = os.path.join(
        app.root_path, app.config['UPLOAD_FOLDER'], song.filename)
    os.remove(song_path)

    # delete the song from database
    db.session.delete(song)
    db.session.commit()

    flash(f'Song `{song_title}` has been deleted!', 'success')
    return redirect(url_for('main.home'))


@songs.route('/song/download/<int:song_id>', methods=['GET'])
@login_required
def download(song_id):
    song = Song.query.get_or_404(song_id)
    if current_user != song.owner:
        abort(403)

    song_path = os.path.join(app.config['UPLOAD_FOLDER'], song.filename)

    if not os.path.exists(song_path):
        flash("Song file not found on server", "error")
        return redirect(url_for('main.home'))

    title, artist, album = song.title, song.artist, song.album

    response = send_file(song_path, as_attachment=True,
                         download_name=f'{title}.mp3', mimetype='audio/mp3')

    response.headers['Content-Type'] = 'audio/mpeg'
    response.headers['Content-Disposition'] = f'attachment; filename="{title}.mp3"'
    response.headers['Cache-Control'] = 'no-cache'
    response.headers['X-Accel-Redirect'] = f'/download/{song.filename}'

    return response


@songs.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    form = SearchForm()
    if form.validate_on_submit():
        search_input_text = form.search_input_text.data
        results = Song.query.filter(
            or_(Song.title.ilike('%{}%'.format(search_input_text)),
                Song.artist.ilike('%{}%'.format(search_input_text)),
                Song.album.ilike('%{}%'.format(search_input_text)))).all()

        if results:
            return render_template('search_results.html', songs=results, search_input_text=search_input_text, form=form)
        return render_template('search_results.html', search_input_text=search_input_text, form=form)

    return render_template('search.html', form=form)

musicapp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, logout_user, current_user, login_required
from musicapp.models import User
from musicapp import bcrypt, db
from musicapp.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from musicapp.users.utils import send_password_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Account Successfully Created! Please login to continue.', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        flash('Login Failed! Please check email and password.', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)


@users.route('/reset_password', methods=['GET', 'POST'])
def password_reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_password_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('password_reset_request.html', title="Reset Password", form=form)


@users.route('/reset_password/<string:token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    user = User.verify_reset_token(token)
    if user is None:
        flash('Token is invalid or expired!', 'warning')
        return redirect(url_for('users.password_reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! Please login to continue.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', title="Reset Password", form=form)

musicapp/templates/collection.html
{% extends "layout.html" %}
{% block content %}
  {% if songs.items %}
    <legend class="border-bottom mb-4">
      All Songs
    </legend>
    <article class="media content-section">
      <div class="media-body">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Artist</th>
              <th scope="col">Album</th>
            </tr>
          </thead>
          <tbody>
            {% for song in songs.items %}
              <tr class="my-4">
                <td scope="row">{{ ((songs.page - 1) * songs.per_page) + loop.index }}</td>
                <td>
                  <a href="{{ url_for('songs.song', song_id=song.id) }}"
                     class="song-body text-decoration-none">{{ song.title }}</a>
                </td>
                <td>{{ song.artist }}</td>
                <td>{{ song.album }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        {% if songs.pages > 1 %}
          <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
              {% for page_num in songs.iter_pages() %}
                {% if page_num %}
                  {% if songs.page == page_num %}
                    <li class="page-item active">
                      <a class="page-link"
                         href="{{ url_for('main.collection', page=page_num) }}">{{ page_num }}</a>
                    </li>
                  {% else %}
                    <li class="page-item">
                      <a class="page-link"
                         href="{{ url_for('main.collection', page=page_num) }}">{{ page_num }}</a>
                    </li>
                  {% endif %}
                {% else %}
                  <li class="page-item disabled">
                    <span class="page-link">...</span>
                  </li>
                {% endif %}
              {% endfor %}
            </ul>
          </nav>
        {% endif %}
      </div>
    </article>
  {% else %}
    <h2>All songs will appear here</h2>
    <p class="text-muted">Please upload songs by clicking on upload button!</p>
  {% endif %}
{% endblock content %}

musicapp/templates/home.html
{% extends "layout.html" %}
{% block content %}
  {% if songs.items %}
    <legend class="border-bottom mb-4">
      Your Songs
    </legend>
    <article class="media content-section">
      <div class="media-body">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Artist</th>
              <th scope="col">Album</th>
            </tr>
          </thead>
          <tbody>
            {% for song in songs.items %}
              <tr class="my-4">
                <td scope="row">{{ ((songs.page - 1) * songs.per_page) + loop.index }}</td>
                <td>
                  <a href="{{ url_for('songs.song', song_id=song.id) }}"
                     class="song-body text-decoration-none">{{ song.title }}</a>
                </td>
                <td>{{ song.artist }}</td>
                <td>{{ song.album }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        {% if songs.pages > 1 %}
          <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
              {% for page_num in songs.iter_pages() %}
                {% if page_num %}
                  {% if songs.page == page_num %}
                    <li class="page-item active">
                      <a class="page-link" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                    </li>
                  {% else %}
                    <li class="page-item">
                      <a class="page-link" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                    </li>
                  {% endif %}
                {% else %}
                  <li class="page-item disabled">
                    <span class="page-link">...</span>
                  </li>
                {% endif %}
              {% endfor %}
            </ul>
          </nav>
        {% endif %}
      </div>
    </article>
  {% else %}
    <h2>Your songs will appear here.</h2>
    <p class="text-muted">Please upload songs by clicking on upload button!</p>
  {% endif %}
{% endblock content %}

musicapp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous"/>
    <link rel="stylesheet"
          type="text/css"
          href="{{ url_for('static', filename='main.css') }}"/>
    {% if title %}
      <title>MusicLib - {{ title }}</title>
    {% else %}
      <title>MusicLib</title>
    {% endif %}
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">MusicLib</a>
          <button class="navbar-toggler"
                  type="button"
                  data-toggle="collapse"
                  data-target="#navbarToggle"
                  aria-controls="navbarToggle"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.collection') }}">Collection</a>
                <a class="nav-item nav-link" href="{{ url_for('songs.upload') }}">Upload</a>
              {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav ms-auto">
              {% if current_user.is_authenticated %}
                <form class="form-inline my-2 my-lg-0 d-flex justify-content-evenly"
                      action="{{ url_for('songs.search') }}"
                      method="post">
                  {{ form.hidden_tag() }}
                  <input type="search"
                         name="search_input_text"
                         placeholder="Enter song title, artist or ablum.."
                         aria-label="Search"
                         class="form-control me-2"
                         required/>
                  <button type="submit" class="btn btn-dark">Search</button>
                </form>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main"
          class="container d-flex justify-content-center align-items-center">
      <div class="col-md-8">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if
            messages %}
            {% for category, message in messages %}<div class="alert alert-{{ category }}">{{ message }}</div>{% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock content %}
      </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
            integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
            integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
            crossorigin="anonymous"></script>
  </body>
</html>

musicapp/templates/login.html
{% extends "layout.html" %}
{% block content %}
  <div class="content-section">
    <form method="post">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">
          Log In
        </legend>
        <div class="form-group mb-3">
          {{ form.email.label(class='form-control-label') }}
          {% if form.email.errors %}
            {{ form.email(class='form-control form-control-lg is-invalid') }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.email(class='text-muted form-control form-control-lg') }}
          {% endif %}
        </div>
        <div class="form-group mb-3">
          {{ form.password.label(class='form-control-label') }}
          {% if form.password.errors %}
            {{ form.password(class='form-control form-control-lg is-invalid') }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.password(class='form-control form-control-lg') }}
          {% endif %}
        </div>
        <div class="form-check mb-3">
          {{ form.remember(class='form-check-input') }}
          {{ form.remember.label(class='form-check-label') }}
        </div>
      </fieldset>
      <div class="form-group mb-2">{{ form.submit(class='btn btn-outline-info') }}</div>
      <small class="text-muted ml-2">
        <a href="{{ url_for('users.password_reset_request') }}">Forgot Password?</a>
      </small>
    </form>
  </div>
  <div class="border-top pt-3">
    <small class="text-muted">
      Need An Account?
      <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a>
    </small>
  </div>
{% endblock content %}

musicapp/templates/password_reset_request.html
{% extends "layout.html" %}
{% block content %}
  <div class="content-section">
    <form method="post">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">
          Reset Password
        </legend>
        <div class="form-group mb-3">
          {{ form.email.label(class='form-control-label') }}
          {% if form.email.errors %}
            {{ form.email(class='form-control form-control-lg is-invalid') }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}<span>{{ error }}</span>{% endfor %}
            </div>
          {% else %}
            {{ form.email(class='text-muted form-control form-control-lg') }}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group mb-2">{{ form.submit(class='btn btn-outline-info') }}</div>
    </form>
  </div>
{% endblock content %}

musicapp/templates/search_results.html
{% extends "layout.html" %}
{% block content %}
  {% if songs %}
    <legend class="border-bottom mb-4">
      Search results for '{{ search_input_text }}'
    </legend>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">Artist</th>
          <th scope="col">Album</th>
        </tr>
      </thead>
      <tbody>
        {% for song in songs %}
          <tr class="my-4">
            <td scope="row">{{ loop.index }}</td>
            <td>
              <a href="{{ url_for('songs.song', song_id=song.id) }}"
                 class="song-body text-decoration-none">{{ song.title }}</a>
            </td>
            <td>{{ song.artist }}</td>
            <td>{{ song.album }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <h2>No results found for "{{ search_input_text }}"</h2>
    <p class="text-muted">Please try searching something else!</p>
  {% endif %}
{% endblock content %}

musicapp/templates/song.html
{% extends "layout.html" %}
{% block content %}
  {% if song %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <legend class="mb-1">
            {{ song.title }}
          </legend>
          <p class="text-muted">
            By <strong>{{ song.artist }}</strong> from <strong>{{ song.album }}</strong>
          </p>
        </div>
        <audio controls
               autoplay
               loop
               controlslist="nodownload"
               class="w-100 mt-2 mb-2">
          <source src="{{ music }}" type="audio/mp3"/>
          <source src="{{ music }}" type="audio/mpeg"/>
          <source src="{{ music }}" type="audio/wav"/>
          Your browser does not support the audio tag.
        </audio>
        <div class="btns">
          <a class="btn btn-outline-info"
             href="{{ url_for('songs.download', song_id = song.id) }}">Download</a>
          {% if song.owner == current_user %}
            <button type="button"
                    class="btn btn-outline-danger m-2"
                    data-bs-toggle="modal"
                    data-bs-target="#deleteModalCenter">
              Delete
            </button>
          {% endif %}
        </div>
      </div>
    </article>
    <!-- Modal -->
    <div class="modal fade"
         id="deleteModalCenter"
         tabindex="-1"
         aria-labelledby="deleteModalCenterTitle"
         aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLongTitle">Delete Song?</h5>
            <button type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"></button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <form action="{{ url_for('songs.delete', song_id=song.id) }}" method='post'>
              <input type="submit" class="btn btn-danger" value="Delete" />
            </form>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <h2>Song does not exist!</h2>
    <p class="text-muted">Try to play other songs.</p>
  {% endif %}
{% endblock content %}